### ISSUE TITLE
So ähnlich wie?…

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/httpheader#1]
https://github.com/FriendsOfREDAXO/http_headers
Wollt ihr nicht evtl. zusammen arbeiten?

**Comment by olien** [comment]
Da eine doppelte Entwicklung irgendwie doof ist magst du hier die issues übernehmen?

https://github.com/FriendsOfREDAXO/http_headers/issues

**Comment by iceman-fx** [comment]
Meins steht nicht im Installer 😀
Aber wir können gern beide zusammenführen.

**Comment by iceman-fx** [comment]
Machst du an deinem überhaupt noch etwas?

**Comment by olien** [comment]
Wollte ich eigentlich schon. Aber jetzt ;-)

**Comment by skerbis** [comment]
super Jungs

**Comment by iceman-fx** [comment]
@olien lass uns nächste Woche Mal hierzu reden, was wir wo wie zusammenführen.

**Comment by olien** [comment]
Ich habe mein AddOn aus dem Installer genommen und archiviert.
