### ISSUE TITLE
Kurze Erklärung zu den einzelnen Eistellungen?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/httpheader#2]
wie bei https://github.com/FriendsOfREDAXO/http_headers :-)

**Comment by iceman-fx** [comment]
Du meinst sicher die Modalboxen?

**Comment by olien** [comment]
Ja. Oder findest Du das nicht gut. Können ja auch accordions oder so sein.

**Comment by iceman-fx** [comment]
Das ist schon gut. Brauch man vielleicht nicht bei jedem Header. Ich würde das bei denen machen, wo es Optionen gibt.
Die Header stellt eh keiner ein, der dies nicht kennt.
