### ISSUE TITLE
Evtl. eine Kennzeichnung zur "Gefährlichkeit"?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/httpheader#3]
grün = keine Probleme zu erwarten
gelb = kann Probleme machen
rot = ups. war ich das etwa?

wie bei https://github.com/FriendsOfREDAXO/http_headers :-)

**Comment by iceman-fx** [comment]
Häh?
Welche Farben?

**Comment by olien** [comment]
Ich habe um die jeweilige Einstellung einen farbigen Rahmen. Rot ist grad nicht aktiv…

**Comment by iceman-fx** [comment]
Ach, diesen dünnen Rahmen meinst Du.
Ich könnte mir da keinen Reim draus machen und dachte, es ist aus Designgründen.
