### ISSUE TITLE
CSP: connect-src und/oder zusätzliches freies Eingabefeld

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/httpheader#7]
Erstmal vorweg.
Super tolles Addon !!!
Leider erst vor kurzem entdeckt.
Vielen Dank für die Entwicklung !!!

Ich hätte eine Frage bzw. einen Ergänzungswunsch.

Bei der Content Security Police (CSP):

Könnte man **connect-src** und **manifest-src** noch ergänzen ?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/manifest-src

Und zusätzlich noch ein weiterer **freies Eingabefeld**, welches nicht wie bisher alternativ zu den Auswahlfeldern ist, sondern ergänzend Werte hinzugefügt.
Also so, dass man weiterhin alles auswählen kann und zusätzlich noch eigene Angaben hinten dranhängt.
Wie z.B. in meinem Fall:
connect-src https://www.google-analytics.com;
manifest-src 'self';

So muss man nicht alles selber schreiben, sondern braucht den fehlenden Eintrag nur ergänzen.

Wäre das machbar ?
Sollte ich irgendwie helfen können, dann kurz schreiben.

Noch eine andere Anmerkung: 
Das alternative Eingabefeld ("Eingabefeld anstatt Auswahl nutzen") ist glaube ich aktuell auf 250 Zeichen beschränkt. 
Ich habe aber zum Teil deutlich längere Anweisungen, die werden dann abgeschnitten.
Könnte man die Anzahl der Zeichen dort erhöhen ?

Und nochmals, super Addon !!!
Vielen DANK dafür !!!
Mirco

**Comment by iceman-fx** [comment]
Das Textfeld von den Zeichen her zu vergrößern ist kein Problem.
Aber ergänzend zu den anderen Feldern? Das könnte zu Dopplungen führen.

**Comment by iceman-fx** [comment]
Ich habe nun ein neues Realeas rausgeschoben.
Da ist sowohl die Zeichenbeschränkung raus, als auch die Möglichkeit der connect-src & manifest-src-Hinterlegung drin.
